### ISSUE TITLE
[Bug] AttributeError on Preview Frame [sf#226]

### ISSUE THREAD

**Issue by DietmarSchwertberger** [DietmarSchwertberger/wxGlade#297]
**Reported by hraban on 2017-12-18 08:54 UTC**
Even in the simplest apps (just one empty frame) preview doesn’t work.
~~~
ERROR   : None
An unexpected error occurred!

Exception type:      <type 'exceptions.AttributeError'>
Exception details:   'module' object has no attribute 'invalidate_caches'

Application stack traceback:
  File "/usr/local/lib/wxPython-3.0.0.0/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py", line 16767, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File ".../workspace/wxglade/new_properties.py", line 2307, in __call__
    self.callback(*args, **kwargs)
  File ".../workspace/wxglade/edit_windows.py", line 680, in on_preview
    self.preview_widget = common.app_tree.app.preview(self)
  File ".../workspace/wxglade/application.py", line 418, in preview
    importlib.invalidate_caches()

Date and time:       2017-12-18T09:52:47.387114
Python version:      2.7.13
wxPython version:    3.0.0.0
wxWidgets platform:  __WXMAC__
wxGlade version:     0.8.0a9
~~~

**Comment by DietmarSchwertberger** [comment]
**Commented by hraban on 2017-12-18 10:48 UTC**
It works with Python 3.6.0 and wxPython 4.0.0b2

**Comment by DietmarSchwertberger** [comment]
**Updated by dschwertberger on 2017-12-18 18:05 UTC**
- **status**: open --> accepted
- **assigned_to**: Dietmar Schwertberger

**Comment by DietmarSchwertberger** [comment]
**Commented by dschwertberger on 2017-12-18 18:05 UTC**
Thanks for reporting.
It seems that `invalidate_caches` is only available for revisions >=3.3.
This line was mainly added for testing. Hopefully omitting it for Python 2 will not cause too many problems on previewing.

**Comment by DietmarSchwertberger** [comment]
**Updated by dschwertberger on 2017-12-18 19:16 UTC**
- **status**: accepted --> closed

**Comment by DietmarSchwertberger** [comment]
**Commented by dschwertberger on 2017-12-18 19:16 UTC**
Fixes are in 0.8.0a13, which is online now.
